name: push to hatena blog

on: 
  push:
    branches-ignore:
      - master

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - uses: actions/cache@v1
      with:
        path: ~/go/bin/
        key: ${{ runner.os }}-go-blogsync-200423.0756
        restore-keys: |
          ${{ runner.os }}-go-blogsync-200423.0756

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: git fetch origin master

    - name: Setup blogsync
      env:
        BSY: ${{ secrets.BSY }}
      run: |
        if !(type ~/go/bin/blogsync > /dev/null 2>&1); then
          go get github.com/x-motemen/blogsync;
        fi
        echo -e ${BSY} > blogsync.yaml

    - name: push
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        git diff origin/master --name-only \
        | grep entries/${DOMAIN}/entry \
        | xargs -t -n1 ~/go/bin/blogsync push

    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@master
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}