name: push to hatena blog

on:
  push:
    branches-ignore:
      - main

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - uses: actions/cache@v3s
      with:
        path: ~/go/bin/
        key: ${{ runner.os }}-go-blogsync
        restore-keys: |
          ${{ runner.os }}-go-blogsync

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - run: git fetch origin main

    - name: Setup blogsync
      env:
        BSY: ${{ secrets.BSY }}
      run: |
        if !(type ~/go/bin/blogsync > /dev/null 2>&1); then
          go install github.com/x-motemen/blogsync;
        fi
        echo -e ${BSY} > blogsync.yaml

    - name: push
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        git diff origin/main --name-only \
        | grep entries/${DOMAIN}/entry \
        | xargs -t -n1 ~/go/bin/blogsync push

    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@main
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}